### ISSUE TITLE
Org switch does not work in 6.x

### ISSUE THREAD

**Issue by dpotapov** [digiapulssi/grafana-organisations-panel#10]
The plugin seems working in 6.x in general, but button links are broken.

**Comment by sanchomuzax** [comment]
Similar problem on v6.5.0 (commit: 24a5d2f)

**Comment by timyllym** [comment]
This is now fixed and waiting for aproval to Grafana plugin repository.

**Comment by sanchomuzax** [comment]
It solved by Grafana v6.5.1-1 👍
