### ISSUE TITLE
Bad rendering when there are many project buttons to draw

### ISSUE THREAD

**Issue by dpotapov** [digiapulssi/grafana-organisations-panel#15]
Please take a look into this screenshot:

![image](https://user-images.githubusercontent.com/5475708/73571391-0751a200-4434-11ea-9639-493c8722a2f9.png)

When the plugin renders a second line of buttons, they are clashing with each other. Some vertical spacing would help.
Thanks.

**Comment by timyllym** [comment]
I made a change so it should work now. It will take a while for the Grafana plugin repository to accept the update though.
