### ISSUE TITLE
Problem with Grafana 5.0

### ISSUE THREAD

**Issue by sanchomuzax** [digiapulssi/grafana-organisations-panel#5]
Please, update it to the Grafana 5.0 final version. 
This doesn't work with the new version.

Thank you!

**Comment by kompa3** [comment]
Created PULSSI-1148 ticket out of this, fyi @timyllym

**Comment by sjdy521** [comment]
+1 Grafana 5.0 expected

**Comment by timyllym** [comment]
New version is now in Grafana plugins repository. Sorry about delay.

**Comment by sanchomuzax** [comment]
Thank you, tested, working. Please, close it. :)
