### ISSUE TITLE
[bug] Conflict with Grafana v5.2.0-1 

### ISSUE THREAD

**Issue by sanchomuzax** [digiapulssi/grafana-organisations-panel#9]
Grafana version: grafana.x86_64 0:5.2.0-1

Dashboard message after updated the Grafana:

~~~
Plugin Error
Fetch error: 401 Instantiating https://localhost/public/vendor/plugin-css/css.js Loading https://localhost/public/vendor/plugin-css/css.js Instantiating https://localhost/public/plugins/digiapulssi-organisations-panel/style.css!https://localhost/public/vendor/plugin-css/css.js Loading https://localhost/public/plugins/digiapulssi-organisations-panel/organisations_ctrl.js Loading plugins/digiapulssi-organisations-panel/module
~~~

**Comment by timyllym** [comment]
Ok, thanks for letting me know. But do you know what is causing the error? Problem with css-file name or class-name?

**Comment by timyllym** [comment]
@sanchomuzax ^

**Comment by sanchomuzax** [comment]
Unfortunately, I don't know what the cause is. There're similar operating errors for other plugins. There is something that works, but the css is wrong.

https://github.com/grafana/piechart-panel/issues/152
https://github.com/michaeldmoore/michaeldmoore-annunciator-panel/issues/3

**Comment by sanchomuzax** [comment]
After the css cache or proxy was empty, the plugin re-started to work. Thank you!
